project:
  type: book

book:
  title: "数理统计"
  author: "Casella"
  date: "2026/6/13"
  chapters:
    - index.qmd
    - chapters/1.md

number-depth: 3

format:
  docx:
    from: markdown+tex_math_dollars+tex_math_single_backslash
    # toc-depth: 3
