project:
  type: book

book:
  title: "线性代数导论（第 5 版）"
  author: "Strang"
  date: "2026/6/27"
  chapters:
    - index.qmd
    - chapters/1.md
    - chapters/2.md
    - chapters/3.qmd
    # - chapters/4.qmd
    - chapters/12.md
  appendices:
    - appendices/3.1.qmd
    - appendices/3.2.qmd
    - appendices/3.3.qmd
    - appendices/3.5.qmd

format:
  docx: default
  html:
    include-in-header:
      file: ../../assets/main-header.html

from: markdown+tex_math_single_backslash
number-depth: 2
