project:
  type: book

book:
  title: "线性代数导论（第5版）"
  author: "Strang"
  date: "2026/6/27"
  chapters:
    - index.qmd
    - chapters/1.md
    - chapters/2.md
    - chapters/12.md

format:
  docx: default
