project:
  type: book

book:
  title: "高等数学第8版（同济大学数学科学学院）"
  # author: "Norah Jones"
  date: "2026/6/13"
  chapters:
    - index.qmd
    - chapters/3.md
  appendices:
    - appendices/Series.md
    - appendices/泰勒公式的顶级理解.md

format:
  docx: default
