project:
  type: book

book:
  title: "MIT 18.06 Linear Algebra"
  author: "Strang"
  date: "2026/6/27"
  chapters:
    - index.qmd
    - chapters/1.md
    - chapters/2.md
    - chapters/3.md
    - chapters/4.md
    - chapters/5.md
    - chapters/6.md
    - chapters/7.md
    - chapters/8.qmd
    - chapters/c1.md
    - chapters/c2.md
  appendices:
    - appendices/LUsolve方法.md
    - appendices/Echelon_form & RREF.md
    - appendices/7.md
    - appendices/8.md

number-depth: 2
from: markdown+tex_math_single_backslash

format:
  html:
    css: ../../../assets/main.css
    # include-in-header:
    #   file: ../../../assets/main-header.html
  docx:
    toc-depth: 2

# math-method: mathjax
# include-in-header:
#   text: |
#     \usepackage{amsmath}
