project:
  type: book

book:
  title: "MIT 18.06 Linear Algebra"
  author: "Strang"
  date: "2026/6/27"
  chapters:
    - index.qmd
    - chapters/1.md
  appendices:
    - appendices/LUsolve方法.md
    - appendices/Echolen_form & RREF.md

number-depth: 2

format:
  docx: default
